force-app/main/default/objects/Integration__c/Integration__c.object-meta.xml
<CustomObject>
    <description>US TP - Custom Object to securely store settings such as passwords and tokens</description>
    <label>Integration</label>
    <nameField>
        <label>Integration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration__c/fields/Authentication_Token__c.field-meta.xml
<CustomField>
    <fullName>Authentication_Token__c</fullName>
    <description>US TP - to store the security token to access the api</description>
    <label>Authentication Token</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Integration__c/fields/Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Base_Url__c</fullName>
    <description>US TP - to store the endpoint base url</description>
    <label>Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetIntegrationCredentials.cls
/**
 * @description       : 
 * @author            : Tom Philippou
 * @last modified on  : 10-01-2022
 * @last modified by  : Tom Philippou
 * Modifications Log
 * Ver   Date         Author          Modification
 * 1.0   10-01-2022   Tom Philippou   Initial Version
**/
public class GetIntegrationCredentials {
    @AuraEnabled(cacheable=true)
    public static Integration__c getCredentials(String integrationName){
        return [SELECT Id, Authentication_Token__c, Base_Url__c FROM Integration__c WHERE Name = :integrationName];
    }
}