force-app/main/default/objects/Account/fields/CC_Charitable_Object__c.field-meta.xml
<CustomField>
    <fullName>CC_Charitable_Object__c</fullName>
    <description>US TP - updated by Charity Commission</description>
    <inlineHelpText>Updated by Charity Commission</inlineHelpText>
    <label>CC Charitable Object</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Charity_Type__c.field-meta.xml
<CustomField>
    <fullName>CC_Charity_Type__c</fullName>
    <description>US TP - Updated by Charity Commission</description>
    <inlineHelpText>Updated by Charity Commission</inlineHelpText>
    <label>CC Charity Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Date_of_Registration__c.field-meta.xml
<CustomField>
    <fullName>CC_Date_of_Registration__c</fullName>
    <description>CR-US</description>
    <inlineHelpText>Updated by Charities Commission.</inlineHelpText>
    <label>CC Date of Registration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Email__c.field-meta.xml
<CustomField>
    <fullName>CC_Email__c</fullName>
    <description>US TP - updated by Charity Commission</description>
    <inlineHelpText>updated by Charity Commission</inlineHelpText>
    <label>CC Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Full_Charity_Name__c.field-meta.xml
<CustomField>
    <fullName>CC_Full_Charity_Name__c</fullName>
    <description>CR-US</description>
    <inlineHelpText>Updated by Charities Commission.</inlineHelpText>
    <label>CC Full Charity Name</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Other_Names__c.field-meta.xml
<CustomField>
    <fullName>CC_Other_Names__c</fullName>
    <description>US TP - Other Names used by Charity Commission</description>
    <label>CC Other Names</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Phone__c.field-meta.xml
<CustomField>
    <fullName>CC_Phone__c</fullName>
    <description>US TP - updated by Charity Commission</description>
    <inlineHelpText>updated by Charity Commission</inlineHelpText>
    <label>CC Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CC_Registration_Status__c</fullName>
    <description>CR-US</description>
    <inlineHelpText>Updated by Charities Commission.</inlineHelpText>
    <label>CC Registration Status</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Trustees__c.field-meta.xml
<CustomField>
    <fullName>CC_Trustees__c</fullName>
    <description>US TP - Field to hold Trustee information from Charity Commission</description>
    <label>CC Trustees</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Website__c.field-meta.xml
<CustomField>
    <fullName>CC_Website__c</fullName>
    <description>US TP - updated by Charity Commission</description>
    <inlineHelpText>updated by Charity Commission</inlineHelpText>
    <label>CC Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Charity_Reg_Co_Number__c.field-meta.xml
<CustomField>
    <fullName>Charity_Reg_Co_Number__c</fullName>
    <description>US TP</description>
    <label>Charity Reg Co. Number</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_of_Removal__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Removal__c</fullName>
    <description>US TP</description>
    <label>Date of Removal</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Income__c.field-meta.xml
<CustomField>
    <fullName>Income__c</fullName>
    <description>US TP</description>
    <label>Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Reporting_Period_Year_End__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Year_End__c</fullName>
    <description>US TP</description>
    <label>Reporting Period Year End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CharityCommissionComponentControllerTest.cls
/**
 * @description       :
 * @author            : Tom Philippou
 * @last modified on  : 16-09-2021
 * @last modified by  : Tom Philippou
 * Modifications Log
 * Ver   Date         Author          Modification
 * 1.0   16-09-2021   Tom Philippou   Initial Version
 **/
@isTest
public class CharityCommissionComponentControllerTest {
    @isTest
    static void getAccountDetailsTest() {
        TestDataFactory tdf = new TestDataFactory();

        Test.startTest();
        Account acc = CharityCommissionComponentController.getAccountDetails(tdf.testAccount.Id);

        System.assertEquals('Test Charity', acc.Name, 'Account Name doesn\'t match');
        Test.stopTest();
    }

    @isTest
    static void getAccountDetailsTestNegative() {
        TestDataFactory tdf = new TestDataFactory();

        Test.startTest();
        try {
            Account acc = CharityCommissionComponentController.getAccountDetails('23132165484');
        } catch (Exception ex) {
            System.assertEquals('Error has occurred: List has no rows for assignment to SObject', ex.getMessage());
        }
        Test.stopTest();
    }

    @isTest
    static void getSearchByNameCalloutTest() {
        TestDataFactory tdf = new TestDataFactory();

        Test.setMock(HttpCalloutMock.class, new CharityCommissionCalloutMock());

        Test.startTest();
        String returnedCharitiesString = CharityCommissionComponentController.getSearchByNameCallout('Marie Curie');

        System.assert(returnedCharitiesString.contains('"reg_charity_number":508665'), 'Test Failed: wrong JSON retrieved from Mock Callout Class');
        Test.stopTest();
    }

    @isTest
    static void getSearchByNameCalloutTestNegative() {
        //TODO: negative test
    }

    @isTest
    static void getAllCharityDataCalloutTest() {
        TestDataFactory tdf = new TestDataFactory();
        String accountString = JSON.serialize(tdf.testAccount);

        Test.setMock(HttpCalloutMock.class, new CharityCommissionCalloutMock());

        Test.startTest();
        String iawString = CharityCommissionComponentController.getAllCharityDataCallout(accountString);

        System.debug(iawString);
        Test.stopTest();
    }

    @isTest
    static void getAllCharityDataCalloutTestNegative() {
        //TODO: negative test
    }

    @isTest
    static void updateCharityFieldsTest() {
        TestDataFactory tdf = new TestDataFactory();

        String fieldMapString = '{"Phone":"CC_Phone__c","Registration_Status":"CC_Registration_Status__c","Date_of_Removal":"Date_of_Removal__c","Trustees":"CC_Trustees__c","Reporting_Period_Year_End":"Reporting_Period_Year_End__c","Income":"Income__c","Charity_Type":"CC_Charity_Type__c","Email":"CC_Email__c","Charitable_Object":"CC_Charitable_Object__c","Date_of_Registration":"CC_Date_of_Registration__c","Charity_Reg_Co_Number":"Charity_Reg_Co_Number__c","Website":"CC_Website__c","Other_Names":"CC_Other_Names__c","Name":"CC_Full_Charity_Name__c"}';
        Map<String, Object> mapping = (Map<String, Object>) JSON.deserializeUntyped(fieldMapString);
        Map<String, String> stringMap = new Map<String, String>();
        for (String key : mapping.keySet()) {
            String value = String.valueOf(mapping.get(key));
            stringMap.put(key, value);
        }

        Test.startTest();
        WrapperUtility.CharityCommissionComponentWrapper wuCccw = CharityCommissionComponentController.updateCharityFields(tdf.testAccountCharityFields.Id, stringMap);

        System.assertEquals(true, wuCccw.isSuccess, 'Set fields not successful.');
        Test.stopTest();
    }
}