force-app/main/default/objects/Account/fields/Charity_Number__c.field-meta.xml
<CustomField>
    <fullName>Charity_Number__c</fullName>
    <description>CR-US</description>
    <inlineHelpText>Updated by Charities Commission.</inlineHelpText>
    <label>Charity Number</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Charity_Suffix__c.field-meta.xml
<CustomField>
    <fullName>Charity_Suffix__c</fullName>
    <description>US TP</description>
    <label>Charity Suffix</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Charities.recordType-meta.xml
<RecordType>
    <fullName>Charities</fullName>
    <active>true</active>
    <description>Charities Commission</description>
    <label>Charities</label>
</RecordType>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>US TP - to store errors from Integrations</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Error-{00000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>US TP</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>US TP</description>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>US TP</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountFunctions.cls
/**
 * @description       : Method to
 * @author            : Tom Philippou
 * @last modified on  : 11-01-2022
 * @last modified by  : Tom Philippou
 * Modifications Log
 * Ver   Date         Author          Modification
 * 1.0   01-09-2021   Tom Philippou   Initial Version
 **/
public class AccountFunctions {
    public static void getCharities(List<Account> accList) {
        try {
            String charityRT = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Charities').getRecordTypeId();

            Set<Id> newAccountIdSet = new Set<Id>();

            for (Account acc : accList) {
                if (acc.RecordTypeId == charityRT && !String.isBlank(acc.Charity_Number__c) && !String.isBlank(acc.Charity_Suffix__c)) {
                    newAccountIdSet.add(acc.Id);
                }
            }

            System.debug('newAccountIdSet: ' + JSON.serialize(newAccountIdSet));
            if (!newAccountIdSet.isEmpty()) {
                CharityCommissionBatchClassCallout ccbcc = new CharityCommissionBatchClassCallout(newAccountIdSet);
                Database.executeBatch(ccbcc, 40);
            } else {
                return;
            }

            // TODO: do something with accNoCharityNumberList - error log? email?
        } catch (Exception ex) {
            System.debug('AccountFunctions - getCharities');
            System.debug('Error has occurred: ' + ex.getMessage());
            System.debug('Line Number: ' + ex.getLineNumber());
            System.debug('Cause: ' + ex.getCause());

            insert new Error_Log__c(Line_Number__c = ex.getLineNumber(), Error_Message__c = ex.getMessage(), Type__c = 'AccountFunctions - getCharities');
        }
    }
    // test
}